version: "3.9"

services:
  starpi-dev:
    image: sareen/starpi:dev
    container_name: starpi-dev
    ports:
      - "1338:1337"
    environment:
      NODE_ENV: development
    volumes:
      - ../:/app
    restart: unless-stopped
